version: '2.2'

services:

  smap-env:
    network_mode: "host"
    image: smap:env
    container_name: ros2-env
    privileged: true
    depends_on:
      - p3dx
      - p3dx-navigation
    environment:
      - "ROS_DOMAIN_ID=5"
    volumes:
      - /mnt/chopin_02/container_files/rosbags:/workspace/rosbags
      # - /mnt/chopin_02/smap/smap_core:/workspace/src/smap/smap_core
      # - /mnt/chopin_02/smap/interfaces:/workspace/src/smap/interfaces
    command: >
      bash -c "
        sleep 60 &&
        . install/setup.bash && 
        tail -f /dev/null
      "

    # sleep 60 && ros2 launch nav2_bringup slam_launch.py
      
    # tail -f /dev/null

  # . install/setup.bash && 
  #       RMW_IMPLEMENTATION=rmw_cyclonedds_cpp ROS_DOMAIN_ID=5 ros2 launch zed_wrapper zed2.launch.py publish_tf:=false

  # echo export STP=$STP > /workspace/step.init
  # (while [[ -z "${STP2}" ]]; do echo "waiting"; sleep 1; done) & (sleep 2 && export STP2=1)
  # (while [[ "${STP}" != "0" ]]; do echo "waiting"; sleep 1; done) & (sleep 2 && export STP2=1)
  # (while [[ "${STP}" -ne "1" ]]; do echo "waiting"; sleep 1; source step.init; done) & (sleep 5 && echo export STP=1 > step.init)

    # bash -c "
    #     . install/setup.bash && 
    #     (
    #       (
    #         (ros2 launch zed_wrapper zed2.launch.py config_path:=/workspace/config/p3dx.yaml publish_tf:=false cam_pose:=[0.10,0.0,0.84,0.0,0.0,0.0]) && 
    #         ((while $(ros2 topic list | grep -q /zed2/zed_node/rgb/image_rect_color); do sleep 1; done) && (echo export STP=1 > step.init))
    #       ) &
    #       (
    #         (while [[ "${STP}" -ne "1" ]]; do echo "waiting"; sleep 1; source step.init; done) &&
    #         (ros2 launch smap_sampler sampler_launch.py)
    #       )
    #     )
    #   "

    # STP is used to control when a step of the process is completed

    # (ros2 launch zed_wrapper zed2.launch.py config_path:=/workspace/config/p3dx.yaml publish_tf:=false cam_pose:=[0.10,0.0,0.84,0.0,0.0,0.0])
    # tail -f /dev/null
    # (ros2 launch zed_wrapper zed2.launch.py config_path:=/workspace/config/p3dx.yaml publish_tf:=false cam_pose:=[0.0,0.0,0.91,0.0,0.0,0.0])


  p3dx:
    image: lucyannofrota/p3dx-noetic-foxy
    container_name: p3dx
    network_mode: "host"
    privileged: true
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
      - "ROS_DOMAIN_ID=5"
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
    cap_add:
      - SYS_PTRACE
    command: >
      bash -c "    
        (. noetic/devel/setup.bash && roscore) &
        (sleep 15 && . noetic/devel/setup.bash && rosparam load noetic/config/ros1_bridge.yaml && roslaunch p3dx_bringup p3dx_bringup.launch) & 
        (sleep 25 && . foxy/install/setup.bash && ros2 run ros1_bridge parameter_bridge)
      "
    # (sleep 10 && . noetic/devel/setup.bash && rosparam load noetic/config/ros1_bridge.yaml && roslaunch p3dx_bringup p3dx_bringup.launch) & 
    # (sleep 25 && . foxy/install/setup.bash && ros2 run ros1_bridge parameter_bridge)  

    # ros2 launch p3dx_bringup bringup_slam_launch.py

  p3dx-navigation:
    network_mode: "host"
    image: lucyannofrota/p3dx-navigation
    container_name: p3dx-navigation
    privileged: true
    depends_on:
      - p3dx
    environment:
      - "ROS_DOMAIN_ID=5"
    volumes:
      - /mnt/chopin_02/container_files/rosbags:/workspace/rosbags
    command: >
      bash -c "
        sleep 40 && . install/setup.bash && ros2 launch p3dx_bringup bringup_slam_launch.py
      "
    # sleep 40 && . install/setup.bash && ros2 launch p3dx_bringup bringup_slam_launch.py
    # tail -f /dev/null

  smap-sampler:
    network_mode: "host"
    image: lucyannofrota/smap:jetson-sampler-zed
    container_name: smap-sampler-zed
    privileged: true
    depends_on:
      - p3dx-navigation
    environment:
      - "ROS_DOMAIN_ID=5"
    volumes:
      - /mnt/chopin_02/container_files/rosbags:/workspace/rosbags
    command: >
      bash -c "
        sleep 40 && . install/setup.bash && 
        (
          (ros2 launch zed_wrapper zed2.launch.py config_path:=/workspace/config/p3dx.yaml publish_tf:=false cam_pose:=[0.10,0.0,0.84,0.0,0.0,0.0]) & configs:
          (ros2 launch smap_sampler sampler_launch.py)
        )
      "
  # (sleep 40 && . install/setup.bash && ros2 launch smap_sampler sampler_launch.py)

  smap-yolov5:
    network_mode: "host"
    image: lucyannofrota/smap:jetson-yolov5
    container_name: jetson-yolov5
    shm_size: '8gb' # <-- when RUNNING 
    privileged: true
    depends_on:
      - smap-sampler
    environment:
      - "ROS_DOMAIN_ID=5"
    cap_add:
      - SYS_PTRACE
    command: >
      bash -c "
        . install/setup.bash && ros2 launch smap_yolo_v5 yolov5_launch.py
      "
    # ros2 launch smap_yolo_v5 yolov5_launch.py
    # tail -f /dev/null

    
