# Based on https://github.com/gbalke/docker-ros2-opengl

version: '3.7'

services:
  ros2-cuda:
    user: "ros"
    network_mode: "host"
    image: ros2-full-cuda-opengl-gazebo-zed
    container_name: ros2-semantic-mapping
    build:
      network: host
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    privileged: true
    # Not necessary when running in host network mode.
    #ports:
    #  - 8080:8080 # Passthrough for Jupyter Notebook
    #  - 1234:1234 # Passthrough for SSH
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
      # - $PWD/dev:/home/ros/dev
      - ./:/workspaces/Semantic-Mapping-ROS2-Containers/:cached
    cap_add:
      - SYS_PTRACE
    command: sleep infinity
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

