version: '2.2'

services:

  smap-env:
    network_mode: "host"
    image: smap:env
    container_name: ros2-env
    privileged: true
    environment:
      - "ROS_DOMAIN_ID=5"
    volumes:
      - /mnt/chopin_02/container_files/rosbags:/workspace/rosbags
    command: >
      bash -c "
        tail -f /dev/null
      "

  # . install/setup.bash && 
  #       RMW_IMPLEMENTATION=rmw_cyclonedds_cpp ROS_DOMAIN_ID=5 ros2 launch zed_wrapper zed2.launch.py publish_tf:=false

  ros2-zed:
    network_mode: "host"
    image: ros2:zed
    container_name: zed-camera-foxy
    privileged: true
    environment:
      - "ROS_DOMAIN_ID=5"
    volumes:
      - /mnt/chopin_02/container_files/rosbags:/workspace/rosbags
    command: >
      bash -c "
        . install/setup.bash && 
        (ros2 launch zed_wrapper zed2.launch.py config_path:=/workspace/config/p3dx.yaml publish_tf:=false cam_pose:=[0.10,0.0,0.84,0.0,0.0,0.0])
      "
    # (ros2 launch zed_wrapper zed2.launch.py config_path:=/workspace/config/p3dx.yaml publish_tf:=false cam_pose:=[0.10,0.0,0.84,0.0,0.0,0.0])
    # tail -f /dev/null
    # (ros2 launch zed_wrapper zed2.launch.py config_path:=/workspace/config/p3dx.yaml publish_tf:=false cam_pose:=[0.0,0.0,0.91,0.0,0.0,0.0])


  p3dx:
    image: p3dx:noetic-foxy
    container_name: p3dx
    network_mode: "host"
    privileged: true
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
      - "ROS_DOMAIN_ID=5"
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
    cap_add:
      - SYS_PTRACE
    command: >
      bash -c "
        (. noetic/devel/setup.bash && roscore) &
        (sleep 5 && . noetic/devel/setup.bash && rosparam load noetic/config/ros1_bridge.yaml && roslaunch p3dx_bringup p3dx_bringup.launch) & 
        (sleep 10 && . foxy/install/setup.bash && ros2 run ros1_bridge parameter_bridge)  
      "

  # noetic:
  #   image: p3dx:noetic
  #   container_name: noetic
  #   extends:
  #     file: docker-compose-p3dx.yml
  #     service: noetic
  #   network_mode: "host"
  #   privileged: true
  #   environment:
  #     - "DISPLAY"
  #     - "QT_X11_NO_MITSHM=1" #fix some QT bugs
  #   volumes: 
  #     - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
  #     - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
  #   cap_add:
  #     - SYS_PTRACE
  #   command: bash -c "tail -F /dev/null"
  
  # p3dx_noetic:
  #   image: p3dx:noetic-drivers
  #   container_name: p3dx-noetic
  #   extends:
  #     file: docker-compose-p3dx.yml
  #     service: p3dx_noetic
  #   network_mode: "host"
  #   privileged: true
  #   environment:
  #     - "DISPLAY"
  #     - "QT_X11_NO_MITSHM=1" #fix some QT bugs
  #   volumes: 
  #     - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
  #     - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
  #   cap_add:
  #     - SYS_PTRACE
  #   command: bash -c "tail -F /dev/null"

  # noetic_foxy:
  #   image: p3dx:noetic-foxy
  #   container_name: noetic-foxy
  #   extends:
  #     file: docker-compose-p3dx.yml
  #     service: noetic_foxy
  #   network_mode: "host"
  #   privileged: true
  #   environment:
  #     - "DISPLAY"
  #     - "QT_X11_NO_MITSHM=1" #fix some QT bugs
  #   volumes: 
  #     - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
  #     - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
  #   cap_add:
  #     - SYS_PTRACE
  #   command: bash -c "tail -F /dev/null"
  
