version: '2.2'

services:

  smap-env:
    network_mode: "host"
    image: lucyannofrota/smap:jetson-env
    container_name: samp-env
    privileged: true
    depends_on:
      - p3dx
      - p3dx-navigation
    environment:
      - "ROS_DOMAIN_ID=5"
    volumes:
      - /mnt/chopin_02/container_files/rosbags:/workspace/rosbags
      # - /mnt/chopin_02/smap/smap_core:/workspace/src/smap/smap_core
      # - /mnt/chopin_02/smap/interfaces:/workspace/src/smap/interfaces
    command: >
      bash -c "
        sleep 60 &&
        . install/setup.bash && 
        tail -f /dev/null
      "

  smap-sampler:
    network_mode: "host"
    image: lucyannofrota/smap:jetson-sampler-zed
    container_name: smap-sampler-zed
    privileged: true
    depends_on:
      - p3dx-navigation
    environment:
      - "ROS_DOMAIN_ID=5"
    volumes:
      - /mnt/chopin_02/container_files/rosbags:/workspace/rosbags
    command: >
      bash -c "
        sleep 40 && . install/setup.bash && 
        (
          (ros2 launch zed_wrapper zed2.launch.py config_path:=/workspace/config/p3dx.yaml publish_tf:=false cam_pose:=[0.10,0.0,0.84,0.0,0.0,0.0]) & configs:
          (ros2 launch smap_sampler sampler_launch.py)
        )
      "

  smap-yolov5:
    network_mode: "host"
    image: lucyannofrota/smap:jetson-yolov5
    container_name: jetson-yolov5
    shm_size: '8gb' # <-- when RUNNING 
    privileged: true
    depends_on:
      - smap-sampler
    environment:
      - "ROS_DOMAIN_ID=5"
    cap_add:
      - SYS_PTRACE
    command: >
      bash -c "
        . install/setup.bash && ros2 launch smap_yolo_v5 yolov5_launch.py
      "
