# Based on https://github.com/gbalke/docker-ros2-opengl

version: '3.7'

services:

  ros2-zed:
    #user: "ros"
    network_mode: "host"
    image: smap:zed-wrapper
    container_name: zed-wrapper
    build:
      network: host
      context: .
      dockerfile: ./Docker/Dockerfile_zed.dockerfile
    privileged: true
    # Not necessary when running in host network mode.
    #ports:
    #  - 8080:8080 # Passthrough for Jupyter Notebook
    #  - 1234:1234 # Passthrough for SSH

      #https://linuxconfig.org/how-to-move-docker-s-default-var-lib-docker-to-another-directory-on-ubuntu-debian-linux
      # sudo mount --rbind /mnt/docker /var/lib/docker

    cap_add:
      - SYS_PTRACE
    command: bash -c "RMW_IMPLEMENTATION=rmw_cyclonedds_cpp ROS_DOMAIN_ID=7 ros2 launch zed_wrapper zed2.launch.py publish_tf:=false"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  ros2-env:
    user: "ros"
    network_mode: "host"
    image: smap:env
    container_name: smap-env
    build:
      network: host
      context: .
      dockerfile: ./Docker/Dockerfile_env.dockerfile
    privileged: true
    # Not necessary when running in host network mode.
    #ports:
    #  - 8080:8080 # Passthrough for Jupyter Notebook
    #  - 1234:1234 # Passthrough for SSH
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
      - ./:/workspace/:cached
    cap_add:
      - SYS_PTRACE
    command: bash -c "tail -F /dev/null"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  ros2-torch:
    user: "ros"
    network_mode: "host"
    image: smap:ros2-torch
    container_name: smap-torch
    build:
      network: host
      context: .
      dockerfile: ./Docker/Dockerfile_torch.dockerfile
    privileged: true
    # Not necessary when running in host network mode.
    #ports:
    #  - 8080:8080 # Passthrough for Jupyter Notebook
    #  - 1234:1234 # Passthrough for SSH
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
      - ./classifier_data/classifier_1:/workspace/data/:cached
      - ./src/smap/smap_interfaces:/workspace/src/smap/smap_interfaces
      - ./src/smap/smap_classification_wrapper:/workspace/src/smap/smap_classification_wrapper
      - ./src/smap/smap_classifiers:/workspace/src/smap/smap_classifiers
    cap_add:
      - SYS_PTRACE
    command: > 
      bash -c "tail -F /dev/null"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]