version: '2.2'

services:

  smap-env:
    network_mode: "host"
    image: lucyannofrota/smap:jetson-env
    container_name: smap-env
    privileged: true
    depends_on:
      - p3dx
      - p3dx-navigation
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
      - "ROS_DOMAIN_ID=5"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
      - /mnt/chopin_02/container_files/rosbags:/workspace/rosbags
      - /mnt/chopin_02/smap/smap_core:/workspace/src/smap/smap_core
      - /mnt/chopin_02/smap/smap_interfaces:/workspace/src/smap/smap_interfaces
      - /mnt/chopin_02/datasets/timers:/workspace/src/smap/smap_core/timers
      - /mnt/chopin_02/datasets/vals:/workspace/src/smap/smap_core/vals
      - /mnt/chopin_02/datasets/maps:/workspace/src/smap/smap_core/maps
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    restart: unless-stopped
    command: >
      bash -c "
        tail -f /dev/null
      "

  smap-deploy:
    network_mode: "host"
    image: lucyannofrota/smap:jetson-deploy-latest
    container_name: smap-core
    privileged: true
    depends_on:
      - p3dx
      - p3dx-navigation
      - smap-sampler
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
      - "ROS_DOMAIN_ID=5"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    restart: unless-stopped
    command: >
      bash -c "
        . install/setup.bash && ros2 launch smap_node smap_launch.py
      "

  smap-sampler:
    network_mode: "host"
    image: lucyannofrota/smap:jetson-sampler-zed
    container_name: smap-sampler-zed
    privileged: true
    depends_on:
      - p3dx-navigation
    environment:
      - "ROS_DOMAIN_ID=5"
    volumes:
      - /mnt/chopin_02/container_files/rosbags:/workspace/rosbags
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    restart: unless-stopped
    command: >
      bash -c "
        sleep 40 && . install/setup.bash && 
        (
          (ros2 launch zed_wrapper zed2.launch.py config_path:=/workspace/config/p3dx.yaml publish_tf:=false cam_pose:=[0.10,0.0,0.84,0.0,0.0,0.0]) & configs:
          (ros2 launch smap_sampler sampler_launch.py)
        )
      "

  smap-yolov5:
    network_mode: "host"
    image: lucyannofrota/smap:jetson-yolov5
    container_name: jetson-yolov5
    shm_size: '8gb' # <-- when RUNNING 
    privileged: true
    depends_on:
      - smap-sampler
    environment:
      - "ROS_DOMAIN_ID=5"
    volumes:
      - /mnt/chopin_02/datasets/timers:/workspace/timers
    cap_add:
      - SYS_PTRACE
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    restart: unless-stopped
    command: >
      bash -c "
        . install/setup.bash && ros2 launch smap_yolo_v5 yolov5_launch.py
      "
    # . install/setup.bash && (ros2 launch smap_yolo_v5 yolov5_even_launch.py & ros2 launch smap_yolo_v5 yolov5_odd_launch.py)
  smap-yolov5-even:
    network_mode: "host"
    image: lucyannofrota/smap:jetson-yolov5
    container_name: jetson-yolov5-even
    shm_size: '8gb' # <-- when RUNNING 
    privileged: true
    depends_on:
      - smap-sampler
    environment:
      - "ROS_DOMAIN_ID=5"
    volumes:
      - /mnt/chopin_02/datasets/timers:/workspace/timers
    cap_add:
      - SYS_PTRACE
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    restart: unless-stopped
    command: >
      bash -c "
        . install/setup.bash && ros2 launch smap_yolo_v5 yolov5_even_launch.py
      "

  smap-yolov5-odd:
    network_mode: "host"
    image: lucyannofrota/smap:jetson-yolov5
    container_name: jetson-yolov5-odd
    shm_size: '8gb' # <-- when RUNNING 
    privileged: true
    depends_on:
      - smap-sampler
    environment:
      - "ROS_DOMAIN_ID=5"
    volumes:
      - /mnt/chopin_02/datasets/timers:/workspace/timers
    cap_add:
      - SYS_PTRACE
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    restart: unless-stopped
    command: >
      bash -c "
        . install/setup.bash && ros2 launch smap_yolo_v5 yolov5_odd_launch.py
      "
