# Based on https://github.com/gbalke/docker-ros2-opengl

version: '3.7'

services:

  ros2-zed:
    #user: "ros"
    network_mode: "host"
    image: ros2-zed
    container_name: ros2-zed
    build:
      network: host
      context: .
      dockerfile: ./Docker/Dockerfile_zed.dockerfile
    privileged: true
    # Not necessary when running in host network mode.
    #ports:
    #  - 8080:8080 # Passthrough for Jupyter Notebook
    #  - 1234:1234 # Passthrough for SSH
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
      # - $PWD/dev:/home/ros/dev
      #- /Docker/Volumes/zed:/workspaces/zed_
      #- ./mnt/Data/Docker/Volumes/Zed:/workspaces/zed
      #https://linuxconfig.org/how-to-move-docker-s-default-var-lib-docker-to-another-directory-on-ubuntu-debian-linux
      # sudo mount --rbind /mnt/docker /var/lib/docker

    cap_add:
      - SYS_PTRACE
    #command: sleep infinity
    command: >
      bash -c "
        . install/setup.bash &&
        export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp && 
        export ROS_DOMAIN_ID=7 && 
        RMW_IMPLEMENTATION=rmw_cyclonedds_cpp ROS_DOMAIN_ID=7 ros2 launch zed_wrapper zed2.launch.py publish_tf:=false
      "
    #bash -c "
    #  . install/setup.bash &&
    #  export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp && 
    #  export ROS_DOMAIN_ID=7 && 
    #  RMW_IMPLEMENTATION=rmw_cyclonedds_cpp ROS_DOMAIN_ID=7 ros2 launch zed_wrapper zed2.launch.py config_path:='/root/ros2_ws/config/p3dx.yaml'
    #"
    #command: bash -c "ros2 launch zed_wrapper zed2.launch.py"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

  ros2-cuda-base:
    user: "ros"
    network_mode: "host"
    image: ros2-full-cuda-gazebo-turtlebot:desktop
    container_name: ros2-semantic-mapping-env
    build:
      network: host
      context: .
      dockerfile: ./Docker/Dockerfile_env.dockerfile
    privileged: true
    # Not necessary when running in host network mode.
    #ports:
    #  - 8080:8080 # Passthrough for Jupyter Notebook
    #  - 1234:1234 # Passthrough for SSH
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions
      # - $PWD/dev:/home/ros/dev
      - ./:/workspaces/smap-ros2-docker/:cached
    cap_add:
      - SYS_PTRACE
    command: > 
      bash -c "
        sudo ./workspaces/smap-ros2-docker/setup.bash ;
        export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp ; 
        export ROS_DOMAIN_ID=7 ;
        ./workspaces/smap-ros2-docker/build.bash ;
        tail -F /dev/null
      "
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]