#version: '3.7'

services:

  ros2-zed:
    network_mode: "host"
    image: zed:foxy
    container_name: zed-camera-foxy
    build:
      network: host
      context: .
      dockerfile: ./Docker/Dockerfile_zed.dockerfile
    privileged: true
    # Not necessary when running in host network mode.
    #ports:
    #  - 8080:8080 # Passthrough for Jupyter Notebook
    #  - 1234:1234 # Passthrough for SSH
    environment:
      - "DISPLAY"
      - "QT_X11_NO_MITSHM=1" #fix some QT bugs
    volumes: 
      - /tmp/.X11-unix:/tmp/.X11-unix # Share X11 socket with container
      - $HOME/.Xauthority:/home/ros/.Xauthority # Share X11 permissions

    cap_add:
      - SYS_PTRACE
    command: >
      bash -c "
        . install/setup.bash && 
        export RMW_IMPLEMENTATION=rmw_cyclonedds_cpp && 
        export ROS_DOMAIN_ID=7 && 
        RMW_IMPLEMENTATION=rmw_cyclonedds_cpp ROS_DOMAIN_ID=7 ros2 launch zed_wrapper zed2.launch.py publish_tf:=false
      "